[plugin]
prepend_previewers = [
	{ mime = "image/*", run = "noop" },
]

[open]
prepend_rules = [
	# Archive
	{ mime = "application/{,g}zip", use = [ "extract" ] },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract" ] }
]
